# Generated by Django 5.1 on 2024-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
