# Generated by Django 5.1 on 2024-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_lab', '0002_alter_post_about_text_alter_post_blog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography', models.ImageField(upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
    ]
