# Generated by Django 5.1 on 2024-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_lab', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='название'),
        ),
    ]
