
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5430:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/m_lab




  app:
    build: .
    
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8080:8000'
    depends_on:
      - db
    volumes:
      - .:/code


  redis:
    image: redis:latest
    ports:
      - "6370:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  pg_data:
  redis_data: